sonar.projectKey=archlens-platform_archlens-ai-processing
sonar.organization=archlens-platform
sonar.projectName=archlens-ai-processing
sonar.sources=app/
sonar.tests=tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**
